name: Create Release on Merge

on:
  push:
    branches:
      - 'main'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Determine Release Tag
      id: determine_tag
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "Branch name: $BRANCH_NAME"
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        
        # Execute the JavaScript script to determine the new version tag
        node bump-version.js

    - name: Create Release
      run: |
        NEW_TAG=$(node -e "console.log(require('./package.json').version)")
        gh release create "${NEW_TAG}" \
          --title "${NEW_TAG}" \
          --notes "Release created for branch type: ${NEW_TAG}."

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
